### 로그인 실패 테스트
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "user01",
  "password" : "pass01"
}

### 로그인 성공 테스트
POST http://localhost:8080/login
Content-Type: application/json

{
  "username" : "user01",
  "password" : "1234"
}

### 인증 실패 테스트
POST http://localhost:8080/posts

### 인증 성공 테스트
POST http://localhost:8080/posts
Authorization: Bearer eyJkYXRlIjoxNzE1OTM0MzkzNjEyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsInJvbGUiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6InVzZXIwMSIsImV4cCI6MTcxNTkzNzk5M30._FIgyA64FSI-hR5WdUy-ehuCE5eP0tT0yZWc3eO9gYXezrUJCjW7WmtpxfgWoKHTp6uQLLNG-LnD1lYrq9sZdg

### 인가 실패 테스트
POST http://localhost:8080/categories
Authorization: Bearer eyJkYXRlIjoxNzE1OTM0MzkzNjEyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsInJvbGUiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6InVzZXIwMSIsImV4cCI6MTcxNTkzNzk5M30._FIgyA64FSI-hR5WdUy-ehuCE5eP0tT0yZWc3eO9gYXezrUJCjW7WmtpxfgWoKHTp6uQLLNG-LnD1lYrq9sZdg